[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "apigee_client"
version = "0.0.1"
authors = [
  { name="Ken Solorzano-Farrier", email="kener.solorzano@icloud.com" },
]
description = "A Python client library for interacting with the Apigee Edge API, designed to simplify API management and integration tasks."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GNU"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/kensolfar/apigee_client"
Issues = "https://github.com/kensolfar/apigee_client/issues"